/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112741-gcd7b352c53-20231112"
#endif /* AVUTIL_FFVERSION_H */
